const projectsData = [
    {
        name:"Auto Allure - 2023",
        img:"/images/allure-rent.png",
        subTitle:"www.allure-rent-a-car.com",
        title:"Car Rental Website",
        notes:"Live project for a car rental company. Built using NextJS and React",
        gitUrl:"https://github.com/alekosomegas/allure-rent-car",
        url:"https://www.allure-rent-a-car.com",
    },
    {
        name:"Allure Taxi - 2023",
        img:"/images/taxi.jpg",
        subTitle:"www.taxi-allure.com",
        title:"Taxi Company Website",
        notes:" Built Nextjs, react",
        gitUrl:"https://github.com/alekosomegas/TaxiWeb",
        url:"https://allure-taxi-web-app.vercel.app/",
    },
    {
        name:"Taxi Application - 2022",
        img:"/images/taxi-app2.png",
        subTitle:"Java, JavaFX, SQLite ",
        title:"Software for a taxi company",
        notes:"Management of taxi rides, drivers, clients and the fleet with automated invoice generator.",
        gitUrl:"https://github.com/alekosomegas/TaxiApp",
        url: false,
    },
    {
        name:"Attractor - 2023",
        img:"/images/attractor.png",
        subTitle:" Python, Matplotlib",
        title:"Application for Mathematical Research",
        notes:"Developed for a Mathematician to help calculate and plot various functions.",
        gitUrl:"https://github.com/alekosomegas/attractor",
        url: false,
    },
    {
        name:"Web Scrapper - 2023",
        img:"/images/web-scrapper.png",
        subTitle:"Java",
        title:"Web Scrapper for car rental prices",
        notes:"Visits local websites to retrieve quotes for car rentals and gives suggestions on price",
        gitUrl:"https://github.com/alekosomegas/rental-rates",
        url: false,
    },
    {
        name:"Card Game - 2021",
        img:"/images/biriba.png",
        subTitle:"Java, JavaFX ",
        title:"An app based on a card game.",
        notes:"First attempt was with Python, my aim was to experiment with OPP concepts. This version is the Java implementation",
        gitUrl:"https://github.com/alekosomegas/biriba",
        url: false,
    },
]

module.exports = projectsData